---
title: "Estimates - simulated data"
author: "HAEM AALBORG"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This vignettes shows how to use the functions of the ccostr package to verify the estimates in the ccmean function 

- Data is simulated two different ways
- something
- someth8nhg


## Simulation of data

$$M_i = M_i(0)+b_iT_i^L+\sum^{10}_{j=1}\tau_{ij}(min[\{T_i^L-(j-1)\}^+,1])+d_iI(T_i\leq10)$$

```{r}
library(ccostr)
library(parallel)
library(msm)
library(dplyr)
library(survival)
library(knitr)

nSim   <- 1
nYears <- 10

## true mean for unif is 40000 and 
## true mean for exp is 35956 (Bang & Tsiatis, 2000)

unif_light <- lapply(1:nSim, function(x) simCostData(dist = "unif", censor = "light", L=nYears))
unif_heavy <- lapply(1:nSim, function(x) simCostData(dist = "unif", censor = "heavy", L=nYears))
exp_light <- lapply(1:nSim, function(x) simCostData(dist = "exp", censor = "light", L=nYears))
exp_heavy <- lapply(1:nSim, function(x) simCostData(dist = "exp", censor = "heavy", L=nYears))
IDM_none <- lapply(1:nSim, function(x) sim.patients(n = 100, censor = 0, cost = 100))
IDM_light <- lapply(1:nSim, function(x) sim.patients(n = 100, censor = 0.05, cost = 100))
IDM_heavy <- lapply(1:nSim, function(x) sim.patients(n = 100, censor = 0.1, cost = 100))
```

## Controlling estimates

```{r}

### Estimate from censored data
nCores <- 1
cl <- makeCluster(nCores)
clusterExport(cl = cl, c("unif_light", "unif_heavy", "exp_light", "exp_heavy", "IDM_none", "IDM_light", "IDM_heavy"))
clusterEvalQ(cl = cl, {
  library(dplyr)
  library(ccostr)
  library(survival)})
est_unif_light <- parLapply(cl, unif_light, function(x) ccmean(x$censoredCostHistory))
est_unif_heavy <- parLapply(cl, unif_heavy, function(x) ccmean(x$censoredCostHistory))
est_exp_light  <- parLapply(cl, exp_light, function(x) ccmean(x$censoredCostHistory))
est_exp_heavy  <- parLapply(cl, exp_heavy, function(x) ccmean(x$censoredCostHistory))
est_IDM_none   <- parLapply(cl, IDM_none, function(x) ccmean(x$censoredCostHistory))
est_IDM_light  <- parLapply(cl, IDM_light, function(x) ccmean(x$censoredCostHistory))
est_IDM_heavy  <- parLapply(cl, IDM_heavy, function(x) ccmean(x$censoredCostHistory))
stopCluster(cl)

## Summarize
results_unif_light <- do.call(rbind, lapply(est_unif_light, function(x) x[[2]]))
results_unif_heavy <- do.call(rbind, lapply(est_unif_heavy, function(x) x[[2]]))
results_exp_light  <- do.call(rbind, lapply(est_exp_light, function(x) x[[2]]))
results_exp_heavy  <- do.call(rbind, lapply(est_exp_heavy, function(x) x[[2]]))
results_IDM_none   <- do.call(rbind, lapply(est_IDM_none, function(x) x[[2]]))
results_IDM_light  <- do.call(rbind, lapply(est_IDM_light, function(x) x[[2]]))
results_IDM_heavy  <- do.call(rbind, lapply(est_IDM_heavy, function(x) x[[2]]))

results_true <- data.frame("unif_light" = 40000,
                           "unif_heavy" = 40000,
                           "exp_light"  = 35956,
                           "exp_heavy"  = 35956,
                           "IDM_none"   = exact.cost(0.2, 0.5, 0.1, 100)$value,
                           "IDM_light"  = exact.cost(0.2, 0.5, 0.1, 100)$value,
                           "IDM_heavy"  = exact.cost(0.2, 0.5, 0.1, 100)$value)

results_mean <- data.frame("unif_light" = mean(sapply(unif_light, function(x) mean(x$totalCost))),
                           "unif_heavy" = mean(sapply(unif_heavy, function(x) mean(x$totalCost))),
                           "exp_light"  = mean(sapply(exp_light, function(x) mean(x$totalCost))),
                           "exp_heavy"  = mean(sapply(exp_heavy, function(x) mean(x$totalCost))),
                           "IDM_none"   = NA,
                           "IDM_light"  = NA,
                           "IDM_heavy"  = NA)

results_bias <- data.frame("unif_light" = (colMeans(results_unif_light)),
                           "unif_heavy" = (colMeans(results_unif_heavy)),
                           "exp_light"  = (colMeans(results_exp_light)),
                           "exp_heavy"  = (colMeans(results_exp_heavy)),
                           "IDM_none"   = (colMeans(results_IDM_none)),
                           "IDM_light"  = (colMeans(results_IDM_light)),
                           "IDM_heavy"  = (colMeans(results_IDM_heavy)))

results <- rbind(results_true, results_mean, results_bias)
row.names(results) <- c("true_mean", "simulation_mean", colnames(results_unif_light))
kable(results)
```


